export const permissionKeys = [
  'users.read',
  'users.create',
  'users.update',
  'users.delete',

  'roles.read',
  'roles.create',
  'roles.update',
  'roles.delete',

  'permissions.read',
  'permissions.create',

  'facilities.read',
  'facilities.create',
  'facilities.update',
  'facilities.delete',
  'facilities.approve',

  'courts.read',
  'courts.create',
  'courts.update',
  'courts.delete',

  'facilityStaff.read',
  'facilityStaff.create',
  'facilityStaff.delete',

  'facilityApplications.read',
  'facilityApplications.approve',

  'memberships.read',
  'memberships.create',
  'memberships.update',
  'memberships.delete',

  'bookings.read',
  'bookings.create',
  'bookings.update',
  'bookings.delete',

  'payments.read',
  'payments.create',
  'payments.update',
  'payments.delete',

  'audit.read',
  'analytics.read',

  'services.read',
  'services.create',
  'services.update',
  'services.delete',
] as const;

export const systemRoles = [
  {
    name: 'SUPER_ADMIN',
    description: 'Full system access.',
    permissionKeys: permissionKeys as readonly string[],
  },
  {
    name: 'FACILITY_OWNER',
    description: 'Owns facilities and manages staff and courts within owned facilities.',
    permissionKeys: [
      'facilities.read',
      'facilities.create',
      'facilities.update',
      'courts.read',
      'courts.create',
      'courts.update',
      'facilityStaff.read',
      'facilityStaff.create',
      'facilityStaff.delete',
      'bookings.read',
      'bookings.create',
      'bookings.update',
      'memberships.read',
      'memberships.create',
      'memberships.update',
      'payments.read',
      'payments.create',
      'payments.update',
      'analytics.read',
      'services.read',
      'services.create',
      'services.update',
      'services.delete',
    ],
  },
  {
    name: 'FACILITY_ADMIN',
    description: 'Manage facilities and bookings.',
    permissionKeys: [
      'facilities.read',
      'facilities.update',
      'courts.read',
      'courts.create',
      'courts.update',
      'bookings.read',
      'bookings.create',
      'bookings.update',
      'memberships.read',
      'analytics.read',
      'services.read',
      'services.create',
      'services.update',
      'services.delete',
    ],
  },
  {
    name: 'FINANCE_OFFICER',
    description: 'Manage payments and reports.',
    permissionKeys: ['payments.read', 'payments.create', 'payments.update', 'analytics.read', 'audit.read'],
  },
  {
    name: 'OPERATIONS_MANAGER',
    description: 'Operations oversight for schedules and facilities.',
    permissionKeys: [
      'facilities.read',
      'facilities.update',
      'bookings.read',
      'bookings.create',
      'bookings.update',
      'memberships.read',
      'memberships.update',
      'analytics.read',
      'audit.read',
      'services.read',
      'services.create',
      'services.update',
      'services.delete',
    ],
  },
  {
    name: 'COACH_TEAM_MANAGER',
    description: 'Manage team bookings and view members.',
    permissionKeys: ['bookings.read', 'bookings.create', 'bookings.update', 'memberships.read'],
  },
  {
    name: 'COMMUNITY_PLAYER',
    description: 'Basic access.',
    permissionKeys: ['bookings.read'],
  },
  {
    name: 'SERVICE_PROVIDER',
    description: 'External service provider.',
    permissionKeys: ['bookings.read', 'facilities.read', 'services.read', 'services.create', 'services.update', 'services.delete'],
  },
] as const;
